extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - eslint-config-prettier
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
plugins:
  - simple-import-sort
settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.jsx', '.tsx']
      moduleDirectory: ['node_modules', '.']
rules:
  react/react-in-jsx-scope: off
  simple-import-sort/imports: warn
  simple-import-sort/exports: warn
